topology:
  default_network:
    name: b0
    subnet: 192.168.0.0/24
    gateway: 192.168.0.254
  networks:
  - name: b1
    type: bridge
  nodes:
  - name: srl01
    type: srlinux
    memory: 2Gi
    cpu: 500m
    interfaces:
    - name: e1-1
      network: b1
